{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hextris.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: ""
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: {{ include "hextris.fullname" . }}
                port:
                  number: 80
{{- end }}